def run(bot):
    bot.move_forward(50)
    bot.wait(3)
    bot.move_backward(50)
    bot.wait(3)
    bot.turn_counter_clockwise(50)
    bot.wait(3)
    bot.turn_clockwise(50)
    bot.wait(3)
    bot.stop()
